title: Suvam Kharel
theme: jekyll-theme-minimal

logo: profile.jpg
description: |
  B.S. Computer Science | May 2025  
  Southern New Hampshire University

  Welcome to my GitHub Pages portfolio!

show_downloads: false
