title: Suvam Kharel

remote_theme: pages-themes/cayman@v0.2.0

logo: profile DP.jpg
description: |
  B.S. Computer Science | May 2025  
  Southern New Hampshire University

  Welcome to my GitHub Pages portfolio!

show_downloads: false
