title: Suvam Kharel
theme: jekyll-theme-minimal

logo: profile DP.jpg
description: |
  Welcome to my GitHub Pages portfolio!  
  

show_downloads: false

#links
github: https://github.com/suvam-16
linkedin: https://www.linkedin.com/in/suvam-kharel-a6757b191/
